# Generated by Django 5.2.7 on 2025-11-05 03:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorie',
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModelSzablonowy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pole_char', models.CharField(help_text='Standardowe pole na krótki tekst, np. tytuł.', max_length=255, verbose_name='Pole tekstowe (krótkie)')),
                ('pole_text', models.TextField(blank=True, help_text='Pole na długi tekst, np. opis.', null=True, verbose_name='Pole tekstowe (długie)')),
                ('pole_slug', models.SlugField(help_text="Używane do URLi, np. 'moj-artykul-1'.", max_length=100, unique=True)),
                ('pole_int', models.IntegerField(default=0, verbose_name='Liczba całkowita')),
                ('pole_positive_int', models.PositiveIntegerField(default=1, help_text='Tylko liczby dodatnie (>= 0).')),
                ('pole_float', models.FloatField(blank=True, help_text='Liczba zmiennoprzecinkowa (używaj ostrożnie).', null=True)),
                ('pole_decimal', models.DecimalField(decimal_places=2, help_text='Używaj tego do pieniędzy, aby uniknąć błędów zaokrągleń.', max_digits=10, verbose_name='Liczba dziesiętna (dla finansów)')),
                ('pole_boolean', models.BooleanField(default=True, help_text='Przechowuje True lub False.', verbose_name='Pole Tak/Nie')),
                ('pole_boolean_null', models.BooleanField(blank=True, null=True, verbose_name='Pole Tak/Nie/Nieznane')),
                ('pole_date', models.DateField(default=django.utils.timezone.now, help_text='Przechowuje tylko datę.')),
                ('pole_datetime', models.DateTimeField(auto_now=True, help_text='Przechowuje datę i czas.')),
                ('pole_datetime_created', models.DateTimeField(auto_now_add=True, help_text='Data utworzenia.')),
                ('pole_time', models.TimeField(blank=True, help_text='Przechowuje tylko czas.', null=True)),
                ('pole_duration', models.DurationField(blank=True, help_text="Przechowuje okres czasu (np. '3 dni, 4 godziny').", null=True)),
                ('pole_email', models.EmailField(blank=True, max_length=254, verbose_name='Adres E-mail')),
                ('pole_url', models.URLField(blank=True, verbose_name='Adres URL')),
                ('pole_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Unikalny Identyfikator UUID')),
                ('pole_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adres IP (v4 lub v6)')),
                ('pole_file', models.FileField(blank=True, null=True, upload_to='uploads/files/%Y/%m/%d/', verbose_name='Plik')),
                ('pole_image', models.ImageField(blank=True, height_field='obraz_height', null=True, upload_to='uploads/images/%Y/%m/%d/', verbose_name='Obraz', width_field='obraz_width')),
                ('obraz_height', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('obraz_width', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('pole_json', models.JSONField(blank=True, default=dict, help_text='Przechowuje dane w formacie JSON.', null=True)),
                ('pole_foreign_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='szablony', to='App.kategoria', verbose_name='Relacja Wiele-do-Jednego (Klucz Obcy)')),
                ('pole_many_to_many', models.ManyToManyField(blank=True, help_text='Np. tagi.', related_name='szablony_m2m', to='App.kategoria', verbose_name='Relacja Wiele-do-Wielu')),
                ('pole_one_to_one', models.OneToOneField(help_text='Np. profil użytkownika.', on_delete=django.db.models.deletion.CASCADE, related_name='model_szablonowy', to=settings.AUTH_USER_MODEL, verbose_name='Relacja Jeden-do-Jednego')),
            ],
            options={
                'verbose_name': 'Model Szablonowy',
                'verbose_name_plural': 'Modele Szablonowe',
                'ordering': ['-pole_datetime_created'],
                'indexes': [models.Index(fields=['pole_char', 'pole_date'], name='App_modelsz_pole_ch_487c0a_idx')],
                'unique_together': {('pole_char', 'pole_slug')},
            },
        ),
    ]
